Repository AY1920S1-CS2103T-T11-1/main, pull requests merged in 2019-10, with the labels that each got.

#80 Further integration of Time into Moolah: Implement full time functionality in Expense class and automatic deletion of outdated Events
  src/main/java/seedu/address/commons/core/AliasMappings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListEventsCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Timekeeper.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/expense/Event.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/Reminder.java
  src/main/java/seedu/address/model/expense/Timestamp.java
  src/main/java/seedu/address/model/expense/UniqueEventList.java
  src/main/java/seedu/address/model/expense/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/expense/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicateExpenseAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalExpensesAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/expense/TimestampTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/testutil/EditExpenseDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/ExpenseUtil.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: priority.High

#89 Implement Statistics Compare Feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/commands/StatsCompareCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/logic/parser/StatsCompareCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/expense/Timestamp.java
  src/main/java/seedu/address/model/statistics/Statistics.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/StatsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StatsCompareCommandParserTest.java
Labels: priority.High

#93 Add support for syntax highlighting and some basic autofill
  build.gradle
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SyntaxHighlightTextArea.java
  src/main/java/seedu/address/ui/SyntaxTextDemo.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/syntax-highlighting.css
Labels: feature.GUI

#100 Refactor Expense to accept exactly 1 Category
  docs/DeveloperGuide.adoc
  docs/templates/helpers.rb
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/expense/Event.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/statistics/Statistics.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCategory.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ExpenseListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditExpenseDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/category/CategoryTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditExpenseDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/ExpenseUtil.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: priority.High

#105 Further develop Events: Add Events using 'add' command, add popups to convert transpired Events to Expenses
  src/main/java/seedu/address/commons/core/AliasMappings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SwitchBudgetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Timekeeper.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/expense/Event.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TranspiredEventsWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/TranspiredEventsWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddBudgetCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/AliasTestUtil.java
  src/test/java/seedu/address/testutil/ExpenseUtil.java
Labels: priority.High, status.Ongoing

#117 Update UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddExpenseOrEventActivityDiagram.puml
  docs/diagrams/ExpenseClassDiagram.puml
  docs/diagrams/TranspiredEventsSequenceDiagram.puml
  docs/images/AddExpenseOrEventActivityDiagram.png
  docs/images/TranspiredEventsSequenceDiagram.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.High

#132 Further time-related developments: Integrate Natty with MooLah and allow Date & Time inputs
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Timekeeper.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/expense/Timestamp.java
  src/main/java/seedu/address/model/statistics/TabularStatistics.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TranspiredEventsWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/budget/BudgetCard.java
  src/main/java/seedu/address/ui/expense/ExpenseCard.java
  src/test/data/JsonSerializableMooLahTest/duplicateExpenseMooLah.json
  src/test/data/JsonSerializableMooLahTest/typicalExpensesMooLah.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/budget/BudgetTest.java
  src/test/java/seedu/address/model/expense/TimestampTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/TypicalBudgets.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: priority.High

#158 Minor changes to Events and populate Sample MooLah with Events
  src/main/java/seedu/address/model/Timekeeper.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/TranspiredEventsWindow.java
Labels: priority.High
